# Generated by Django 3.1.3 on 2020-12-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0002_auto_20201205_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_comparison_sparepart',
            name='sp_type',
            field=models.CharField(choices=[('ground_engaging_tools', 'ground_engaging_tools'), ('manganese_liners', 'manganese_liners'), ('mechanical_parts', 'mechanical_parts')], default='mechanical_parts', max_length=50),
        ),
    ]
