# Generated by Django 3.1.3 on 2020-12-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0003_auto_20201205_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_comparison_sparepart',
            name='sp_type',
            field=models.CharField(choices=[('ground engaging tools', 'ground engaging tools'), ('manganese liners', 'manganese liners'), ('mechanical parts', 'mechanical parts')], default='mechanical parts', max_length=50),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='sp_type',
            field=models.CharField(choices=[('ground engaging tools', 'ground engaging tools'), ('manganese liners', 'manganese liners'), ('mechanical parts', 'mechanical parts')], default='mechanical parts', max_length=50),
        ),
    ]
